global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

scrape_configs:
  - job_name: compute
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/compute.json
        refresh_interval: 1m

  - job_name: blackbox
    metrics_path: /probe
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/blackbox.json
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [prober_address]
        target_label: __address__
      - action: labeldrop
        regex: prober_address

  - job_name: blackbox-exporter
    static_configs:
      - targets:
          - 192.168.255.11:9115
        labels:
          probe_from: faszyn
      - targets:
          - 192.168.254.11:9115
        labels:
          probe_from: szew
