[WebService]
Origins = https://cockpit.faszyn.lan.bajojajo.com wss://cockpit.faszyn.lan.bajojajo.com https://cockpit.szew.lan.bajojajo.com wss://cockpit.szew.lan.bajojajo.com
ProtocolHeader = X-Forwarded-Proto
RequireHost = false
LoginTo = false
AllowMultiHost = false

[Session]
WarnBeforeConnecting = false

[basic]
action = remote-login-ssh

[Ssh-Login]
host = host.docker.internal
connectToUnknownHosts = true
