[WebService]
Origins = https://cockpit.faszyn.lan.bajojajo.com wss://cockpit.faszyn.lan.bajojajo.com https://cockpit.szew.lan.bajojajo.com wss://cockpit.szew.lan.bajojajo.com
ProtocolHeader = X-Forwarded-Proto
RequireHost = true
LoginTo = true
